# Generated by Django 5.2 on 2025-04-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='Profile'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('staff', 'Staff'), ('vendor', 'Vendor'), ('user', 'User')], default='user', max_length=200),
        ),
    ]
