# Generated by Django 5.2 on 2025-04-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Policies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hotel_info", models.CharField(blank=True, max_length=500)),
                (
                    "cancellation_policy",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "pets_allowed",
                    models.CharField(
                        blank=True,
                        choices=[("Yes", "Yes"), ("No", "No")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "pets_detail",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("check_in_time", models.TimeField(blank=True, null=True)),
                ("check_out_time", models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
