# Generated by Django 5.2 on 2025-04-11 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Policies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policies",
            name="check_in_time",
            field=models.TimeField(blank=True, default=datetime.time(9, 0), null=True),
        ),
        migrations.AlterField(
            model_name="policies",
            name="check_out_time",
            field=models.TimeField(blank=True, default=datetime.time(9, 0), null=True),
        ),
    ]
