# Generated by Django 5.2 on 2025-04-15 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_remove_specialservice_price'),
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelpolicy',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='HotelPolicies', to='hotels.hotel'),
            preserve_default=False,
        ),
    ]
