# Generated by Django 5.2 on 2025-06-04 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0004_address_latitude_address_longitude"),
        ("policies", "0002_hotelpolicy_hotel"),
    ]

    operations = [
        migrations.CreateModel(
            name="CancellationPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "policy_type",
                    models.CharField(
                        choices=[
                            (
                                "flexible",
                                "Flexible (Free cancellation up to 24h before check-in)",
                            ),
                            (
                                "standard",
                                "Standard (48h before check-in, partial refund)",
                            ),
                            ("saver", "Saver (Non-refundable)"),
                        ],
                        default="standard",
                        max_length=100,
                    ),
                ),
                (
                    "cancellation_fee",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "refund_percentage",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="CancellationPolicies",
                        to="hotels.hotel",
                    ),
                ),
            ],
        ),
    ]
