# Generated by Django 5.2 on 2025-04-11 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("hotels", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gst_number", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "pan_card",
                    models.FileField(
                        blank=True, null=True, upload_to="legal_documents/pan_card/"
                    ),
                ),
                (
                    "hotel_license",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="legal_documents/hotel_license/",
                    ),
                ),
                (
                    "ownership_proof",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="legal_documents/ownership_proof/",
                    ),
                ),
                (
                    "fssai_license",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="legal_documents/fssai_license/",
                    ),
                ),
                (
                    "fire_safety",
                    models.FileField(
                        blank=True, null=True, upload_to="legal_documents/fire_safety/"
                    ),
                ),
                (
                    "identity_proof",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="legal_documents/identity_proof/",
                    ),
                ),
                (
                    "managers_proof",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="legal_documents/managers_proof/",
                    ),
                ),
                (
                    "authorization_letter",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="legal_documents/authorization_letter/",
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="legal_documents",
                        to="hotels.hotel",
                    ),
                ),
            ],
        ),
    ]
