# Generated by Django 5.2 on 2025-04-15 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelmedia',
            name='file',
            field=models.FileField(upload_to='gallery/hotel_media/'),
        ),
        migrations.AlterField(
            model_name='roomtypemedia',
            name='file',
            field=models.FileField(upload_to='gallery/room_media/'),
        ),
    ]
