# Generated by Django 5.2 on 2025-04-26 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraServiceCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_service_charges', to='hotels.hoteldetail')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.specialservice')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modes', models.JSONField(default=list)),
                ('hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_modes', to='hotels.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='RoomPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('extra_guest_threshold', models.IntegerField()),
                ('extra_guest_per_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('room_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hotels.room')),
            ],
        ),
    ]
