# Generated by Django 5.2 on 2025-04-04 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hotel",
            fields=[
                ("Hotel_ID", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(blank=True, max_length=200)),
                ("Price", models.CharField(blank=True, max_length=200)),
                ("Description", models.TextField(blank=True)),
                ("Total_No_of_Rooms", models.IntegerField(blank=True, null=True)),
                ("Safety_Features", models.TextField(blank=True)),
                ("Address", models.CharField(blank=True, max_length=200)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("Zip_code", models.IntegerField(blank=True, null=True)),
                ("City", models.CharField(blank=True, max_length=200)),
                ("Nearby_mark", models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Rooms_Type",
            fields=[
                ("Room_ID", models.AutoField(primary_key=True, serialize=False)),
                (
                    "room_type_name",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Single", "Single"),
                            ("Double", "Double"),
                            ("Triple", "Triple"),
                            ("Quad", "Quad"),
                            ("Queen", "Queen"),
                            ("King", "King"),
                            ("Twin", "Twin"),
                            ("Suite", "Suite"),
                        ],
                        max_length=200,
                    ),
                ),
                ("Description", models.CharField(blank=True, max_length=250)),
                ("Occupancy_limit", models.IntegerField(blank=True, null=True)),
                (
                    "Types_of_bed",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Single", "Single"),
                            ("Double", "Double"),
                            ("Triple", "Triple"),
                            ("Quad", "Quad"),
                            ("Queen", "Queen"),
                            ("King", "King"),
                            ("Twin", "Twin"),
                            ("Suite", "Suite"),
                        ],
                        max_length=200,
                    ),
                ),
                ("Price_Per_Night", models.FloatField(blank=True, null=True)),
                ("Amenities", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Room_Details",
            fields=[
                ("Detail_ID", models.AutoField(primary_key=True, serialize=False)),
                ("Price", models.FloatField(blank=True, null=True)),
                (
                    "Available_Rooms",
                    models.CharField(
                        blank=True, choices=[("Yes", "Yes"), ("No", "No")], max_length=3
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hotels.hotel",
                    ),
                ),
                (
                    "room_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hotels.rooms_type",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Amenities",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(blank=True, max_length=200)),
                ("Price", models.FloatField(blank=True, null=True)),
                (
                    "Is_chargeable",
                    models.CharField(
                        blank=True, choices=[("Yes", "Yes"), ("No", "No")], max_length=3
                    ),
                ),
                ("Other_amenities", models.TextField(blank=True)),
                (
                    "Hotel_ID",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hotels.hotel",
                    ),
                ),
                (
                    "Room_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hotels.room_details",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="hotel",
            name="Room_Type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="hotels.rooms_type",
            ),
        ),
    ]
