# Generated by Django 5.2 on 2025-04-11 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hotel",
            fields=[
                ("Hotel_ID", models.AutoField(primary_key=True, serialize=False)),
                ("hotel_name", models.CharField(blank=True, max_length=200)),
                ("owner_name", models.CharField(blank=True, max_length=200)),
                ("phone_number", models.IntegerField(blank=True, null=True)),
                ("email", models.EmailField(blank=True, max_length=200)),
                ("price", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("total_no_of_rooms", models.IntegerField(blank=True, null=True)),
                ("safety_features", models.TextField(blank=True)),
                ("address", models.CharField(blank=True, max_length=200)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("zip_code", models.IntegerField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=200)),
                ("nearby_mark", models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Rooms_Type",
            fields=[
                ("Room_ID", models.AutoField(primary_key=True, serialize=False)),
                (
                    "room_type_name",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Single", "Single"),
                            ("Double", "Double"),
                            ("Triple", "Triple"),
                            ("Quad", "Quad"),
                            ("Queen", "Queen"),
                            ("King", "King"),
                            ("Twin", "Twin"),
                            ("Suite", "Suite"),
                        ],
                        max_length=200,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=250)),
                ("occupancy_limit", models.IntegerField(blank=True, null=True)),
                (
                    "types_of_bed",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Single", "Single"),
                            ("Double", "Double"),
                            ("Triple", "Triple"),
                            ("Quad", "Quad"),
                            ("Queen", "Queen"),
                            ("King", "King"),
                            ("Twin", "Twin"),
                            ("Suite", "Suite"),
                        ],
                        max_length=200,
                    ),
                ),
                ("price_per_night", models.FloatField(blank=True, null=True)),
                ("amenities", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Room_Details",
            fields=[
                ("Detail_ID", models.AutoField(primary_key=True, serialize=False)),
                ("price", models.FloatField(blank=True, null=True)),
                (
                    "available_Rooms",
                    models.CharField(
                        blank=True, choices=[("Yes", "Yes"), ("No", "No")], max_length=3
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hotels.hotel",
                    ),
                ),
                (
                    "room_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hotels.rooms_type",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Amenities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200)),
                ("price", models.FloatField(blank=True, null=True)),
                (
                    "is_chargeable",
                    models.CharField(
                        blank=True, choices=[("Yes", "Yes"), ("No", "No")], max_length=3
                    ),
                ),
                ("other_amenities", models.TextField(blank=True)),
                (
                    "Hotel_ID",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hotels.hotel",
                    ),
                ),
                (
                    "Room_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hotels.room_details",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="hotel",
            name="room_Type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="hotels.rooms_type",
            ),
        ),
    ]
