# Generated by Django 5.2 on 2025-04-15 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialservice',
            name='price',
        ),
    ]
