# Generated by Django 5.2 on 2025-04-18 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0002_remove_specialservice_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="hotel",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="address",
                to="hotels.hotel",
            ),
        ),
    ]
