# Generated by Django 5.2 on 2025-04-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0003_alter_address_hotel"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="address",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
