# Generated by Django 5.2 on 2025-04-25 12:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Search", "0003_wishlist"),
        ("hotels", "0003_alter_address_hotel"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="wishlist",
            unique_together={("user", "hotel")},
        ),
    ]
