# Generated by Django 5.2 on 2025-05-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Search", "0006_bookingamenity_payment"),
        ("hotels", "0004_address_latitude_address_longitude"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="special_requests",
        ),
        migrations.AddField(
            model_name="booking",
            name="guests",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="special_request",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("credit_card", "Credit Card"),
                    ("paypal", "PayPal"),
                    ("bank_transfer", "Bank Transfer"),
                ],
                default=None,
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="special_services",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                related_name="bookings",
                to="hotels.specialservice",
            ),
        ),
    ]
