# Generated by Django 5.2 on 2025-05-27 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Search", "0007_remove_booking_special_requests_booking_guests_and_more"),
        ("hotels", "0004_address_latitude_address_longitude"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="guests",
            new_name="guest_count",
        ),
        migrations.AddField(
            model_name="booking",
            name="room",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="hotels.room",
            ),
        ),
    ]
