# Generated by Django 5.2 on 2025-05-27 11:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Search", "0008_rename_guests_booking_guest_count_booking_room"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="room",
        ),
    ]
