# Generated by Django 5.2 on 2025-05-27 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Search", "0009_remove_booking_room"),
        ("hotels", "0004_address_latitude_address_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="room",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="hotels.room",
            ),
        ),
    ]
