# Generated by Django 5.2 on 2025-05-27 11:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Search", "0010_booking_room"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="guest_count",
            new_name="guests",
        ),
    ]
