# Generated by Django 5.2 on 2025-05-28 06:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Search", "0011_rename_guest_count_booking_guests"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="guests",
            new_name="guest_count",
        ),
    ]
