# Generated by Django 5.2 on 2025-06-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Search", "0012_rename_guests_booking_guest_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="Guest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Female", "female"),
                            ("Male", "Male"),
                            ("kid", "Kid"),
                        ],
                        default="Male",
                        max_length=10,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
            ],
        ),
    ]
