# Generated by Django 5.2 on 2025-06-04 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Search", "0013_guest"),
        ("policies", "0003_cancellationpolicy"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="cancellation_policy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="policies.cancellationpolicy",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("credit_card", "Credit Card"),
                    ("Debit Card", "Debit Card"),
                    ("Phonepay", "Phonepay"),
                    ("Cash", "Cash"),
                ],
                default=None,
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="guest",
            name="booking",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="guests",
                to="Search.booking",
            ),
        ),
    ]
