# Generated by Django 5.2 on 2025-06-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Search", "0014_booking_cancellation_policy_and_more"),
        ("pricing_payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="extra_amentities",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                related_name="bookings",
                to="pricing_payments.extraservicecharge",
            ),
        ),
    ]
