# Generated by Django 5.2 on 2025-06-08 06:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Search", "0015_booking_extra_amentities"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="extra_amentities",
            new_name="extra_amenities",
        ),
    ]
