# Generated by Django 5.2 on 2025-06-12 12:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Search", "0016_rename_extra_amentities_booking_extra_amenities"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("credit_card", "Credit Card"),
                    ("debit_card", "Debit Card"),
                    ("phonepay", "PhonePay"),
                    ("cash", "Cash"),
                ],
                default=None,
                max_length=50,
            ),
        ),
    ]
