# Generated by Django 5.2 on 2025-06-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Search", "0017_alter_payment_amount_alter_payment_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("credit_card", "Credit Card"),
                    ("debit_card", "Debit Card"),
                    ("phonepay", "PhonePay"),
                    ("cash", "Cash"),
                ],
                default="cash",
                max_length=50,
            ),
        ),
    ]
