# Generated by Django 5.2 on 2025-04-05 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("hotels", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Media",
            fields=[
                ("image_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "file_type",
                    models.CharField(
                        blank=True,
                        choices=[("Image", "Image"), ("Video", "Video")],
                        max_length=10,
                    ),
                ),
                ("file_format", models.CharField(blank=True, max_length=10)),
                ("media_file", models.FileField(upload_to="media/")),
                (
                    "hotel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hotels.hotel",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hotels.room_details",
                    ),
                ),
                (
                    "room_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hotels.rooms_type",
                    ),
                ),
            ],
        ),
    ]
