# Generated by Django 5.2 on 2025-04-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Media", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="media",
            name="file_format",
        ),
        migrations.RemoveField(
            model_name="media",
            name="file_type",
        ),
        migrations.RemoveField(
            model_name="media",
            name="media_file",
        ),
        migrations.AddField(
            model_name="media",
            name="hotel_image",
            field=models.FileField(blank=True, null=True, upload_to="media/"),
        ),
        migrations.AddField(
            model_name="media",
            name="room_image",
            field=models.FileField(blank=True, null=True, upload_to="media/"),
        ),
    ]
